config/routes.rb
Rails.application.routes.draw do
  get 'menu' => 'menu#index'

  get 'contacts' => 'contacts#index'

  get '/support' => 'support#new'
  post '/support' => 'support#create'

  root "home#index"

  resources :profiles do
    resources :bookings, only: [:edit, :index, :new, :create, :update, :destroy]
    resources :reviews, only: [:edit, :index, :new, :create, :update, :destroy]
  end

  resources :conversations, only: [:index, :create, :destroy] do
    resources :messages, only: [:new, :create]
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :sender, class_name: 'User'
  validates :content, presence: true

  def user1
    self.conversation.user1
  end

  def user2
    self.conversation.user2
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_conversation
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.where("conversation_id = #{@conversation.id}")
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
    unless (@conversation.user1.id == current_user.id) | (@conversation.user2.id == current_user.id)
      authorize @message
    end
    @messages = Message.where("conversation_id = #{@conversation.id}")
    if @conversation.user1 == current_user
      @receiver = @conversation.user2.first_name + " " + @conversation.user2.last_name
    else 
      @receiver = @conversation.user1.first_name + " " + @conversation.user1.last_name
    end
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)
    @message.conversation = @conversation
    @message.sender = current_user

    respond_to do |format|
      if @message.save
        format.html { redirect_to new_conversation_message_url(@conversation), notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    def set_conversation
      @conversation = Conversation.find(params[:conversation_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:content)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_with(model: [@conversation, message], local: true) do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :message_content %>
  </div>

  <div class="actions">
    <%= form.submit "Send" %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%=  %></h1>

<% @messages.each do |message| %>
  <div class="message-box">
    <p><%= message.content %></p>
  </div>
<% end %>

<br>

<%= link_to 'Send', new_conversation_message_path(@conversation) %>

app/views/messages/new.html.erb
<h1><%= @receiver %></h1>

<% @messages.each do |message| %>
  <% if message.sender == current_user %>
    <div class="message-box right-message-box">
      <p><%= message.content %></p>
    </div>
  <% else %>
    <div class="message-box">
      <p><%= message.content %></p>
    </div>
  <% end %>
<% end %>

<%= render 'form', message: @message %>

<%= link_to 'All Messages', conversations_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Conversation:</strong>
  <%= @message.conversation %>
</p>

<p>
  <strong>Sender:</strong>
  <%= @message.sender %>
</p>

<p>
  <strong>Content:</strong>
  <%= @message.content %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>