config/routes.rb
Rails.application.routes.draw do
  get 'menu' => 'menu#index'

  get 'contacts' => 'contacts#index'

  get '/support' => 'support#new'
  post '/support' => 'support#create'

  root "home#index"

  resources :profiles do
    resources :bookings, only: [:edit, :index, :new, :create, :update, :destroy]
    resources :reviews, only: [:edit, :index, :new, :create, :update, :destroy]
  end

  resources :conversations, only: [:index, :create, :destroy] do
    resources :messages, only: [:new, :create]
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
end

app/models/profile.rb
class Profile < ApplicationRecord
  include ProfileImageUploader[:profile_image]
  belongs_to :user
  validates :price, presence: true
  validates :price, numericality: { greater_than: 0 }
  validates :locations, presence: true

  def self.search(term)
    if term
      # Search through first_name, last_name, board_sport and locations attributes
      Profile.where(user: User.where('first_name ILIKE ?', "%#{term}%")) | Profile.where(user: User.where('last_name ILIKE ?', "%#{term}%")) | where('locations ILIKE ?', "%#{term}%") |where('board_sport ILIKE ?', "%#{term}%")
    else
      all
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.search(params[:term]) & Profile.search(params[:location]) & Profile.search(params[:board])

    @reviews = []
    @profiles.each do |profile|
      @average_rating = Review.where(profile_id: profile).average(:rating)
      @reviews << @average_rating
    end

    # Sort profiles depending on params
    if params[:sort] == 'Rating'
      @profiles.sort_by! do |profile|
        @reviews[profile.id - 1]
      end
      @profiles = @profiles.reverse
    elsif params[:sort] == 'Price(lowest)'
      @profiles.sort_by! do |profile|
        profile[:price]
      end
    elsif params[:sort] == 'Price(highest)'
      @profiles.sort_by! do |profile|
        profile[:price]
      end
      @profiles = @profiles.reverse
    end
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @last_review = Review.where(profile_id: @profile).last
    @average_rating = Review.where(profile_id: @profile).average(:rating)

    # Check if there is an existing conversation between current user and the profile
    @conversation = (Conversation.where(user1_id: @profile.user.id) & Conversation.where(user2_id: current_user.id)) | (Conversation.where(user2_id: @profile.user.id) & Conversation.where(user1_id: current_user.id))

    # If there is no conversation then create a new one
    if @conversation.empty?
      @conversation = Conversation.new
    end

    # Get the all profiles that belong to the user
    @profiles = Profile.where(user: @profile.user)
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)
    @profile.user = current_user

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
      unless current_user.profiles.find_by(id: @profile.id)
        authorize @profile
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:profile_image, :remove_profile_image, :board_sport, :price, :locations, :bio, :description)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :profile_image %>
    <%= form.file_field :profile_image, id: :profile_profile_image %>
  </div>

  <div class="field">
    Remove attachment: <%= form.check_box :remove_profile_image %>
  </div>

  <div class="field">
    <%= form.label :board_sport %>
    <%= form.select :board_sport, ['surfing', 'snow boarding'], id: :profile_board_sport %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, id: :profile_price %>
  </div>

  <div class="field">
    <%= form.label :locations %>
    <%= form.text_field :locations, id: :profile_locations %>
  </div>

  <div class="field">
    <%= form.label :bio %>
    <%= form.text_area :bio, id: :profile_bio %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :profile_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<%= form_tag(profiles_path, method: :get) do %>
  <div class="center search">
    <%= text_field_tag :term, params[:term], placeholder: "Search" %>
  </div>

  <div class="center">
    <div class="select-item">
      <%= select_tag "location", options_for_select(["Point Leo", "Gunnamatta", "Mt. Hotham" ], params[:location]), include_blank: "Location" %>
    </div>

    <div class="select-item">
      <%= select_tag "board", options_for_select(["Surf", "Snow Board" ], params[:board]), include_blank: "Board" %>
    </div>

    <div class="select-item">
      <%= select_tag "sort", options_for_select(["Rating", "Price(lowest)", "Price(highest)" ], params[:sort]), include_blank: "Sort" %>
    </div>
  </div>

<% end %>

<% @profiles.each do |profile| %>
  <%= link_to(profile) do %>
    <div class="center card">
      <h2><%= profile.user.first_name %> <%= profile.user.last_name %></h2>
      <% if profile.profile_image %>
        <%= image_tag profile.profile_image_url(:thumb) %>
      <% end %>
      <h5><%= profile.bio %></h5>
      <p><%= profile.locations %></p>
      <h3>$<%= profile.price %>/hr</h3>
      <% unless @reviews[profile.id - 1].nil? %>
        <h4>Rating: <%= @reviews[profile.id - 1].round %>/5</h4>
      <% else %>
        <p>No Reviews</p>
      <% end %>
    </div>
  <% end %>
<% end %>

<br>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<% if @profile.profile_image %>
  <%= image_tag @profile.profile_image_url(:original) %>
<% end %>

<div class="center flex">
  <h1 class="inline">
    <%= @profile.user.first_name %>
    <%= @profile.user.last_name %> - 
    <%= @profile.board_sport.capitalize %>
  </h1>

  <h3 class="inline">
    Rating: <%= @average_rating.round %>/5
  </h3>
</div>

<h2 class="center">
  $<%= @profile.price %>/hr
</h2>

<p class="center">
  <%= @profile.locations %>
</p>

<p class="center flex">
  <% @profiles.each do |profile| %>
    <%= link_to profile.board_sport, profile %>
  <% end %>
</p>

<h2>Description</h2>
<p>
  <%= @profile.description %>
</p>

<h2>Reviews</h2>
<% unless @profile.user == current_user %>
  <h3>
    <%= @last_review.user.first_name %>
  </h3>

  <p>
    <%= @last_review.content %>
  </p>

  <div>
    <%= link_to "See all reviews", profile_reviews_url(@profile) %> | 
    <%= link_to "Review", new_profile_review_url(@profile) %>
  </div>

  <br>
  <br>


  <%= link_to "Book", new_profile_booking_url(@profile)  %>

  <% if @conversation.kind_of?(Array) %>
    <%= link_to "Message", conversation_messages_url(@conversation) %>
  <% else %>
    <%= form_with(model: @conversation, local: true) do |form| %>

      <%= form.hidden_field :user2_id, :value => @profile.user.id %>

      <div class="actions">
        <%= form.submit "Message" %>
      </div>
    <% end %>
  <% end %>

<% else %>
  <%= link_to edit_profile_path(@profile) do %>
    <img src="<%= image_path("edit.png") %>" alt="edit" width="75" height="75">
  <% end %>
<% end %>