config/routes.rb
Rails.application.routes.draw do
  get 'menu' => 'menu#index'

  get 'contacts' => 'contacts#index'

  get '/support' => 'support#new'
  post '/support' => 'support#create'

  root "home#index"

  resources :profiles do
    resources :bookings, only: [:edit, :index, :new, :create, :update, :destroy]
    resources :reviews, only: [:edit, :index, :new, :create, :update, :destroy]
  end

  resources :conversations, only: [:index, :create, :destroy] do
    resources :messages, only: [:new, :create]
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :user1, class_name: 'User'
  belongs_to :user2, class_name: 'User'
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :set_conversation, only: [:show, :edit, :update, :destroy]

  # GET /conversations
  # GET /conversations.json
  def index
    as_user1 = Conversation.where(user1: current_user)
    as_user2 = Conversation.where(user2: current_user)
    @conversations = as_user1 | as_user2
  end

  # GET /conversations/1
  # GET /conversations/1.json
  def show
  end

  # GET /conversations/new
  def new
    @conversation = Conversation.new
  end

  # GET /conversations/1/edit
  def edit
  end

  # POST /conversations
  # POST /conversations.json
  def create
    @conversation = Conversation.new(conversation_params)
    @conversation.user1 = current_user

    respond_to do |format|
      if @conversation.save
        format.html { redirect_to conversation_messages_url(@conversation) }
        format.json { render :show, status: :created, location: @conversation }
      else
        format.html { render :new }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conversations/1
  # PATCH/PUT /conversations/1.json
  def update
    respond_to do |format|
      if @conversation.update(conversation_params)
        format.html { redirect_to @conversation, notice: 'Conversation was successfully updated.' }
        format.json { render :show, status: :ok, location: @conversation }
      else
        format.html { render :edit }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conversations/1
  # DELETE /conversations/1.json
  def destroy
    @conversation.destroy
    respond_to do |format|
      format.html { redirect_to conversations_url, notice: 'Conversation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conversation
      @conversation = Conversation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def conversation_params
      params.require(:conversation).permit(:user2_id)
    end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_form.html.erb
<%= form_with(model: conversation, local: true) do |form| %>
  <% if conversation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(conversation.errors.count, "error") %> prohibited this conversation from being saved:</h2>

      <ul>
      <% conversation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user2_id %>
    <%= form.collection_select :user2_id, User.where('id != ?', current_user.id), :id, :email, id: :conversation_user2_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/conversations/edit.html.erb
<h1>Editing Conversation</h1>

<%= render 'form', conversation: @conversation %>

<%= link_to 'Show', @conversation %> |
<%= link_to 'Back', conversations_path %>

app/views/conversations/index.html.erb
<p id="notice"><%= notice %></p>

<% @conversations.each do |conversation| %>
  <% unless Message.where("conversation_id = #{conversation.id}").length == 0 %>
    <%= link_to new_conversation_message_path(conversation) do %>
      <p><%= conversation.user2.first_name %></p>
      <%= Message.where("conversation_id = #{conversation.id}").last.content %></p>
      <%= Message.where("conversation_id = #{conversation.id}").last.created_at.hour %>:<%= Message.where("conversation_id = #{conversation.id}").last.created_at.min %>
    <% end %>
  <% end %>
<% end %>

app/views/conversations/new.html.erb
<h1>New Conversation</h1>

<%= render 'form', conversation: @conversation %>

<%= link_to 'Back', conversations_path %>

app/views/conversations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User1:</strong>
  <%= @conversation.user1 %>
</p>

<p>
  <strong>User2:</strong>
  <%= @conversation.user2 %>
</p>

<%= link_to 'Edit', edit_conversation_path(@conversation) %> |
<%= link_to 'Back', conversations_path %>